- id: '1662887095298'
  alias: Water leak
  description: Send notification if there is a water leak
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.water_leak_bathroom_downstairs_water_leak
    from: 'Off'
    to: 'On'
    attribute: water_leak
  - platform: state
    entity_id:
    - binary_sensor.water_leak_bathroom_upstairs_water_leak
    from: 'Off'
    to: 'On'
  condition: []
  action:
  - service: notify.mobile_app_mr_pohoda_iphone_13_mini
    data:
      message: Únik vody dolní nebo horní koupelna
      title: POZOR
  - service: notify.mobile_app_sm_g970f
    data:
      message: Únik vody dolní koupelna
      title: POZOR
  mode: single
- id: '1668612771383'
  alias: OTE < 50
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.ote_min_day_price
    below: 50
  - platform: numeric_state
    entity_id: sensor.ote_min_night_price
    below: 50
  condition: []
  action:
  - service: notify.mobile_app_mr_pohoda_iphone_13_mini
    data:
      message: OTE < 50
  mode: single
- id: '1671803098885'
  alias: Fire detector alarm
  description: Send notification if there is a smoke detected
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.fire_alarm_garage_smoke
    - binary_sensor.fire_alarm_living_room_smoke
    for:
      hours: 0
      minutes: 0
      seconds: 5
    to: 'on'
  condition: []
  action:
  - service: notify.mobile_app_mr_pohoda_iphone_13_mini
    data:
      message: Kouř obývák nebo garáž
      title: POZOR
  - service: notify.mobile_app_sm_g970f
    data:
      message: Kouř obývák nebo garáž
      title: POZOR
  mode: single
- id: '1673441963880'
  alias: OTE rates - update daily
  description: ''
  trigger:
  - platform: time
    at: '13:15:00'
  - platform: time
    at: 05:00:00
  condition: []
  action:
  - service: homeassistant.update_entity
    data: {}
    target:
      entity_id: sensor.ote_rates
  mode: single
- id: '1674675399849'
  alias: Condensation - battery low
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.condensation_under_roof_battery
    to: '3'
  condition: []
  action:
  - service: notify.mobile_app_mr_pohoda_iphone_13_mini
    data:
      message: Condensation - battery low
      title: Home Assistant Automation
  mode: single
- id: '1674889440046'
  alias: Condensation wet detection
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.condensation_under_roof
    from: 'off'
    to: 'on'
  - platform: state
    entity_id:
    - binary_sensor.condensation_host
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: notify.mobile_app_mr_pohoda_iphone_13_mini
    data:
      title: HA - condensation
      message: Wet detected
  mode: single
- id: '1677173286520'
  alias: Light hall motion activated
  description: ''
  use_blueprint:
    path: homeassistant/motion_light.yaml
    input:
      light_target:
        area_id: hall
        device_id: 07d5da5e10b6c8cdecad39fdf4d206e7
        entity_id: light.light_led_hala
      motion_entity: binary_sensor.motion_sensor_hall_up_occupancy
- id: '1677227154536'
  alias: Bojler byt 24h < 1kWh
  description: Kontroluje, jestli se bojler v bytě za poslední 2 dny nahříval.
  trigger:
  - platform: numeric_state
    entity_id: sensor.energy_byt_bojler_used_in_the_last_24_hrs
    below: 1
  condition: []
  action:
  - service: notify.mobile_app_mr_pohoda_iphone_13_mini
    data:
      message: Bojler byt 24h < 1kWh
  mode: single
