- id: '1662887095298'
  alias: Water leak
  description: Send notification if there is a water leak
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.water_leak_bathroom_downstairs_water_leak
    from: 'Off'
    to: 'On'
    attribute: water_leak
  - platform: state
    entity_id:
    - binary_sensor.water_leak_bathroom_upstairs_water_leak
    from: 'Off'
    to: 'On'
  condition: []
  action:
  - service: notify.mobile_app_mr_pohoda_iphone_13_mini
    data:
      message: Únik vody dolní nebo horní koupelna
      title: POZOR
  - service: notify.mobile_app_sm_g970f
    data:
      message: Únik vody dolní koupelna
      title: POZOR
  mode: single
- id: '1671803098885'
  alias: Fire detector alarm
  description: Send notification if there is a smoke detected
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.fire_alarm_garage_smoke
    - binary_sensor.fire_alarm_living_room_smoke
    for:
      hours: 0
      minutes: 0
      seconds: 5
    to: 'on'
  condition: []
  action:
  - service: notify.mobile_app_mr_pohoda_iphone_13_mini
    data:
      message: Kouř obývák nebo garáž
      title: POZOR
  - service: notify.mobile_app_sm_g970f
    data:
      message: Kouř obývák nebo garáž
      title: POZOR
  mode: single
- id: '1693635353057'
  alias: SolaX - locked state
  description: ''
  trigger:
  - platform: state
    entity_id:
    - select.solax_lock_state
    to: Locked
  condition: []
  action:
  - service: notify.mobile_app_mr_pohoda_iphone_13_mini
    data:
      title: Home Assistant
      message: SolaX changed to Locked state
  - service: select.select_option
    metadata: {}
    data:
      option: Unlocked
    target:
      entity_id: select.solax_lock_state
  mode: single
- id: '1702558145516'
  alias: Tablet kiosk - periodical restart
  description: ''
  trigger:
  - platform: time_pattern
    minutes: '15'
  condition: []
  action:
  - service: button.press
    data: {}
    target:
      entity_id: button.lenovo_tab_m8_4th_gen_restart_browser
  mode: single
- id: '1703866232037'
  alias: Sauna temp > 80
  description: ''
  trigger:
  - platform: numeric_state
    entity_id:
    - sensor.esp_temperature_sauna_sauna_inside_temperature
    above: 80
  condition: []
  action:
  - service: notify.mobile_app_mr_pohoda_iphone_13_mini
    data:
      title: Home Assistant
      message: Sauna > 80
  mode: single
- id: '1706011041303'
  alias: SolaX - EPS detected
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.solax_run_mode
    for:
      hours: 0
      minutes: 0
      seconds: 0
    to: EPS
  condition: []
  action:
  - service: notify.mobile_app_mr_pohoda_iphone_13_mini
    data:
      title: HA - SolaX
      message: EPS
  mode: single
- id: '1706266656998'
  alias: Smarwi unavailable
  description: ''
  trigger:
  - platform: state
    entity_id:
    - cover.smarwi_loznice
    to: unavailable
    for:
      hours: 0
      minutes: 5
      seconds: 0
  condition: []
  action:
  - service: notify.mobile_app_mr_pohoda_iphone_13_mini
    data:
      title: HA - Smarwi
      message: Unavailable
  mode: single
- id: '1708420270066'
  alias: Sauna - START
  description: ''
  trigger:
  - platform: time
    at: '17:00:00'
  condition: []
  action:
  - service: switch.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: switch.esp_sauna_sauna_relay_pulz
  - service: notify.mobile_app_mr_pohoda_iphone_13_mini
    data:
      title: HA - sauna
      message: START
  mode: single
- id: '1715335386205'
  alias: ESP sauna - unavailable
  description: ''
  trigger:
  - platform: state
    entity_id:
    - switch.esp_sauna_sauna_relay_pulz
    to: unavailable
    for:
      hours: 0
      minutes: 5
      seconds: 0
  condition: []
  action:
  - service: notify.mobile_app_mr_pohoda_iphone_13_mini
    data:
      title: HA - Sauna
      message: Unavailable
  mode: single
- id: '1721831910914'
  alias: Door - opened too long
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.door_sensor_1_contact
    to: 'on'
    for:
      hours: 0
      minutes: 2
      seconds: 0
  condition: []
  action:
  - service: notify.mobile_app_mr_pohoda_iphone_13_mini
    data:
      title: HA - Front door
      message: Opened > 2 minutes
  mode: single
