- id: '1662887095298'
  alias: Water leak
  description: Send notification if there is a water leak
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.water_leak_bathroom_downstairs_water_leak
    from: 'Off'
    to: 'On'
    attribute: water_leak
  - platform: state
    entity_id:
    - binary_sensor.water_leak_bathroom_upstairs_water_leak
    from: 'Off'
    to: 'On'
  condition: []
  action:
  - service: notify.mobile_app_mr_pohoda_iphone_13_mini
    data:
      message: Únik vody dolní nebo horní koupelna
      title: POZOR
  - service: notify.mobile_app_sm_g970f
    data:
      message: Únik vody dolní koupelna
      title: POZOR
  mode: single
- id: '1668612771383'
  alias: OTE < 50
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.ote_min_day_price
    below: 50
  - platform: numeric_state
    entity_id: sensor.ote_min_night_price
    below: 50
  condition: []
  action:
  - service: notify.mobile_app_mr_pohoda_iphone_13_mini
    data:
      message: OTE < 50
  mode: single
- id: '1671803098885'
  alias: Fire detector alarm
  description: Send notification if there is a smoke detected
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.fire_alarm_garage_smoke
    - binary_sensor.fire_alarm_living_room_smoke
    from: 'on'
    for:
      hours: 0
      minutes: 0
      seconds: 5
  condition: []
  action:
  - service: notify.mobile_app_mr_pohoda_iphone_13_mini
    data:
      message: Kouř obývák nebo garáž
      title: POZOR
  - service: notify.mobile_app_sm_g970f
    data:
      message: Kouř obývák nebo garáž
      title: POZOR
  mode: single
- id: '1673441963880'
  alias: OTE rates - update daily
  description: ''
  trigger:
  - platform: time
    at: '13:15:00'
  condition: []
  action:
  - service: homeassistant.update_entity
    data: {}
    target:
      entity_id: sensor.ote_rates
  mode: single
