
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.0/24
  ip_ban_enabled: true          # use this to enable auto IP ban
  login_attempts_threshold: 3

rflink:
  port: /dev/serial/by-id/usb-Arduino__www.arduino.cc__0042_95038303131351609002-if00
  wait_for_ack: true

automation: !include automations.yaml
mqtt: !include mqtts.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include sensors.yaml

recorder:
  purge_keep_days: 14
  exclude:
    domains:
      - updater
      - media_player
      - device_tracker
      - weather
      - sun
    entity_globs:
      - lock.thermostat_*
      - number.thermostat_*
      - climate.thermostat_*
      - select.thermostat_*
      - sensor.thermostat_*
    event_types:
      - service_registered

logger:
  default: info
  logs:
    rflink: info
    homeassistant.components.rflink: info
    toshiba_ac: info

wake_on_lan:

cover:
  - platform: rflink
    device_defaults:
      fire_event: true
      signal_repetitions: 2
    devices:
      rts_0F0F0F_01:
        name: Blinds kids 1+2
      rts_2F2F2F_01:
        name: Blinds kids 3
      rts_3F3F3F_01:
        name: Blinds kids 4
      rts_4F4F4F_01:
        name: Blinds bedroom 5
      rts_5F5F5F_01:
        name: Blinds bedroom 6

lovelace:
  resources:
    - url: /hacsfiles/numberbox-card/numberbox-card.js
      type: module
      

    