- platform: time_date
  display_options:
    - 'time'
    - 'date'

- platform: rflink
  automatic_add: true


# https://home-assistant.io/components/sensor.template/
# https://www.home-assistant.io/integrations/template#legacy-sensor-configuration-format
- platform: template
  sensors:
    peak_cheapest_price:
      friendly_name: Peak cheapest price
      value_template: >-
        {{ state_attr('sensor.current_market_price_czk_kwh', 'today_hourly_prices')[states('sensor.peak_cheapest_hour')  | int] }}
        
    offpeak_cheapest_price:
      friendly_name: Offpeak cheapest price
      value_template: >-
        {{ state_attr('sensor.current_market_price_czk_kwh', 'today_hourly_prices')[states('sensor.offpeak_cheapest_hour')  | int] }}
    
    day_highest_price:
      friendly_name: Day highest price
      value_template: >-
        {% set highest = namespace({"price":-100}) %}
        {% set items = state_attr('sensor.current_market_price_czk_kwh', 'today_hourly_prices') %}
        {% for i in range(23) %}
          {% if items[i] > highest.price %}
            {% set highest.price = items[i] %}
          {% endif %}
        {% endfor %}
        {{highest.price}}
    
    
    
    senzory_s_bateriou_pod_20:
      friendly_name: Senzory s baterií pod 20%
      value_template: >-
        {%- set domains = ['sensor'] -%}
        {%- set threshold = 20 -%}
        {%- set exclude_entities = ['sensor.iphonepavol_battery_level','sensor.tabletlenovo_battery_level','sensor.tabletlenovofkb_browser_battery'] -%}
        Senzory s baterií pod 20%:
        {%- for domain in domains -%}
          {%- for item in states[domain] | rejectattr('state', 'in', ['unavailable', 'unknown']) -%}
            {%- if item.entity_id not in exclude_entities -%}
              {%- if item.attributes.battery_level is defined -%}
                {%- set level = item.attributes.battery_level|int(0) -%}
                {% if level|int(0) > 0 and level < threshold %}
        - {{ item.attributes.friendly_name }} ({{ item.attributes['battery_level']|int(0)}}%)
                {%- endif -%}
              {%- endif -%}
              {%- if item.attributes.device_class is defined and item.attributes.device_class == 'battery' -%}
                {%- set level = item.state|int(0) -%}
                {% if level > 0 and level <= threshold %}
        - {{ item.attributes.friendly_name }} ({{ item.state|int(0) }}%)
                {%- endif -%}
              {%- endif %}
            {%- endif -%}
          {%- endfor -%}
        {%- endfor -%}
        

